version: '2'
services:
  postgres:
    image: postgres:latest
    volumes:
      - /app/data/postgres:/var/lib/postgresql/data
  web:
    image: jonashungershausen/neurodex:latest
    ports:
      - '8081:8081'
    environment:
      - DATABASE_URL=postgresql://postgres:docker@postgres.local/postgres
    depends_on:
      - postgres
    links:
      - "postgres:postgres.local"
