users:
  - email: admin@neurodex.app
    roles: 
      - ADMIN
      - USER
      - MODERATOR
      - LECTURER
    password: password
  # ..

roles:
  - ADMIN
  - USER
  - MODERATOR
  - LECTURER

jwt:
  secret-key: super-secret