version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
