name: Deploy
on:
  push:
    # branches:
    #   - master
    branches-ignore:
      - '**'
jobs:
  build:
    name: neurodex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test:ci # will run `yarn test` command
      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./coverage/coverage-final.json #optional
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: jonashungershausen/neurodex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./backend/Dockerfile
          tags: 'latest'
      - name: Copy docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./docker-compose.yml"
          target: "/app/docker"
      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: /bin/bash -c "/app/docker/restart.sh"
