name: Release
on:
  release:
    types: [published]
jobs:
  build:
    name: neurodex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neurodex/neurodex
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: deploy/Dockerfile
          tag_semver: true
