name: Run Tests [on PR]
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: neurodex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run eslint ./src/**/*.tsx ./src/**/*.js ./src/**/*.ts
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test:ci # will run `yarn test` command
