name: Run Tests [on PR]
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: neurodex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd ./frontend install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd ./frontend test:ci # will run `yarn test` command
      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./frontend/coverage/coverage-final.json #optional
